#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Chalkhall Overview
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/studyhall/ch-overview.org
:Created:   2017-09-24T09:24@Prek Leap (11.642600N-104.919210W)
:ID:        544702d8-fc92-45f0-baec-fc1a783d63a9
:VER:       559491924.348558149
:GEO:       48P-491193-1287029-15
:BXID:      proj:UTV4-4706
:Class:     deploy
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]




 - Arts        -- what you do
 - Sciences    -- what you know

 - Otium       -- inner
 - Negotium    -- outer

 - Liberal Arts
   - grammer   --
   - logic     --
   - rhetoric  --
   - -----
   - arithmetic 
   - music
   - geometry
   - astronomy

 - Utilitarian Arts
 - Fine Arts


Life is a tightrope walk, balancing between /doing/ and /knowing/.

The path to mastery begins with small steps you learn how to do
something and then learn about it in increasing depth -- theory comes
after you've gotten down the basics.

Modern higher education doesn't do that -- it put's theory first and
then building skills second.  The problem is that this means that
learning is an act of faith, because learning theory without context
is frustrating and feels pointless.  You don't feeling like you are
learning anything useful.  And in practice, by the time you do
graduate and then aquire the skills that theory is supposed to be
based on, you've lost the thread and have forgotten most of the theory.

This makes some sense when learning is something that happens when you
are young and takes place in a continuous block of time before you
enter the workplace.  It's still ass backwards but I get it.

#+begin_comment
Shit and here I am again... I can't seem to do anything
without first coming up with a deep theory to understand how
it all fits together.  /I/ seem to always need theory
first. I'm a fucking mess...

That said, I know now that what has been holding me back on
chalkhall is that I didn't have a general educational model
for lifelong learning.  I'm starting to get a sense of what
that could be.
#+end_comment




* Chalkhall Study Program Overview

Based on [[id:8426aa17-39a9-4714-9070-c133591a0d32][Notes]]

** The Study Program


  - Work on our inhouse OpenStack/OpenShift/Ceph cluster, develop
    applications, assemble infrastructure, manage hardware, and
    running systems.

  - Learn the basics, including /the two editors/, version control,
    shell programing, linux/*nix system and network administration and
    the basics for programing (a SCIP like approach).

  - Learn the cutting edge, and work with a wide variety of
    technologies that are being used to build modern systems that can
    scale.

  - An accredited degree from a National College.  For people living
    in Western countries, it might not sound like much to have a
    degree from a Cambodian University, but it is essential for
    graduates to accept jobs in Cambodia.

  - A study program designed around the concept of "fliping" the
    classroom.  There are no lectures.  Students will read course
    material, and watch videos which will be divided into short 10
    minute or less topics.  Class time will be devoted to answering
    questions, pair-programing exercises, and group projects.

  - A study program which is portfolio-centric.  The idea is for
    students to start from day one, to build a portfolio of code,
    runbooks and experience building and managing real world systems.

  - A study program that spends as much time teaching technology as it
    teaches critical thinking and communication skills.  The idea is
    that a base education teaches people how to think, learn and
    communicate as a foundation for lifelong learning.

  - Campus dorms & workspaces and a group meal every day for students,
    as well as visiting interns and visiting professionals in the
    sabbatical program.

** The Pilot Program

Our initial pilot program will focus on Camodian Women in IT.  The 
first class will be all women.  There are not as many opportunities
for women to find good paying professional jobs anywhere in the world
and this is especially true in South East Asia.

The first class will be made up of ten students, who will help us
develop and test the course material that will be used in the future.

We will invite women students and working professionals from around
the world to work with students through a combination of online
mentorship and in person in Cambodia through, internship and
sabbatical program that last anywhere from a week or two to several
months.

From day one, we will begin promotion of the program to IT companies
in Cambodia.  We will be looking for feed back from companies on what
skills they need today and what they will need in the future and lay
the groundwork so that there will be good jobs waiting for them when
they graduate.


** Funding the program

To fund the pilot program we will approach Remote Only Companies
who have a workforce who works from where they live anywhere around
the world.  Some of the including:

  - GitHub -- version control repository hosting
  - GitLab -- version control repository hosting
  - BaseCamp -- project management & team communication software
  - Automattic -- makers of Wordpress
  - Mozilla -- makers of Firefox Web Browser
  - DataStax -- data management for cloud applications

These companies are the poster children for technical innovation and
Remote Work.  They all have teams spread across the planet.

** The Ask

Sponsor a girl in the pilot program for two years xxx/month and a
laptop.

Provide remote internship to students in their second year.

Ask your employees to become mentors, and participate and sponsor
their participation in our Sabbatical program to come to Cambodia for
anywhere from a couple of weeks to a couple of months to work with
students and on open source software projects.

Provide input and guidence on what skills and technologies that are
needed to work at their companies.

At the end of the program, you have the option of hiring graduates.

Help support our core team through Patreon.

Ask for them to become co-founders of Chenla Institute a Charity
registered in Singapore.


