#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Blended Learning 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/studyhall/sh-blended-learning.org
:Created:   2017-11-07T15:01@Prek Leap (11.642600N-104.919210W)
:ID:        8f723181-692f-45f7-aeb2-e7595ae2c70b
:VER:       563313739.366694089
:GEO:       48P-491193-1287029-15
:BXID:      proj:BEW4-5243
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

We're trying to teach 21C skills using a 19C system based on factory
assembly line....


#+begin_quote
To paraphrase Carol Black; what do we do if a student does a math
problem and they do it perfectly and they do it quickly. Do we praise
them? And she said no, we say, I'm sorry we wasted your time, it was
obviously too easy, let me find something you can learn from.

-- Monique Markoff | [[https://www.youtube.com/watch?v=Mb2d8E1dZjY][TEDxIthacaCollege]]
#+end_quote


 - [[https://en.wikipedia.org/wiki/Blended_learning][Blended learning]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Flipped_classroom][Flipped classroom]] | Wikipedia
 - [[https://www.youtube.com/watch?v=paQCE58334M][Blended learning & flipped classroom]] | open.osmosis.org (YouTube)

 - [[bib:rajan:2013leveraging][Leveraging three pillars of academia through blended learning]] | Amala Rajan (pdf)

 - [[https://www.youtube.com/watch?v=Mb2d8E1dZjY][Blended learning and the future of education]] | Monique Markoff, TEDxIthacaCollege

 - [[http://faculty.washington.edu/kate1/ewExternalFiles/SageOnTheStage.pdf][From Sage on the Stage to Guide on the Side]]  | Alison King (1993) 
   College teaching 41 1: 30–35.
 - Peer Instruction: A User's Manual | Eric Mazur (1996)
 - Inverting the Classroom: A gateway to Creating an
   Inclusive Learning Environment | Maureen Lage (2000)

** Mastery Learning

Mastery learning is the concept of each student working at
their own pace and mastering a topic before moving on.  The
now traditional approach is for everyone in the class to
spend the same amount of time on a topic and move on whether
any individual students have understood the material or not.

#+begin_quote
More recently, the idea of "Flipped Mastery" gained some
popularity. The term was coined by Jon Bergmann and Aaron
Sams, both chemistry teachers. They suggest an
implementation model for Mastery Learning that is mixed with
flipped classroom. The idea is to use technology to
time-shift the individual instruction and eliminate
whole-class lectures. The students watch online lectures and
move through the content at their own pace. In this way
technology frees up the teachers to individualize the
learning for each student.

-- [[https://en.wikipedia.org/wiki/Mastery_learning][Mastery learning]] | Wikipedia
#+end_quote

 - [[https://en.wikipedia.org/wiki/Mastery_learning][Mastery learning]] | Wikipedia
 - [[https://opinionator.blogs.nytimes.com/2013/10/23/in-flipped-classrooms-a-method-for-mastery/?smid=pl-share][In 'Flipped' Classrooms, a Method for Mastery]] | Tina Rosenberg, NYT (2013)
 - [[https://opinionator.blogs.nytimes.com/2013/10/09/turning-education-upside-down/][Turning Education Upside Down]] | Tina Rosenberg, NYT (2013)


** Hungarian Approach

#+begin_quote
In the Hungarian approach to learning and teaching, a strong
and explicit emphasis is placed on problem solving,
mathematical creativity, and communication. Students learn
concepts by working on problems with complexity and
structure that promote perseverance and deep
reflection. These mathematically meaningful problems
emphasize procedural fluency, conceptual understanding,
logical thinking, and connections between various topics.

For each lesson, a teacher selects problems that embody the
mathematical goals of the lesson and provide students with
opportunities to struggle productively towards
understanding. The teacher carefully sequences the problems
to provide focus and coherence to the lesson. These problems
do more than provide students with opportunities to learn
the mathematical topics of a given lesson. Indeed, the
teacher sees the problems she poses as vehicles for
fostering students’ reasoning skills, problem solving, and
proof writing, just to name a few. An overarching goal of
every lesson is for students to learn what it means to
engage in mathematics and to feel the excitement of
mathematical discovery. Click here for a sample task from a
5th grade classroom at Fazekas Mihály School in Budapest.

Another hallmark of the Hungarian approach is the classwide
discussion of approaches to problems. After working on
problems individually or in small groups, volunteers come to
the front of class to share their solutions. Because of the
non-trivial nature of these problems, students learn to
communicate their thinking with clarity and precision. When
a student gets stuck, others chime in to offer support and
suggestions in a friendly manner. The teacher creates a
welcoming environment that is conducive to the sharing of
students’ mathematical experiences.

In such a classroom, the teacher’s role is that of a
motivator and facilitator. He provides encouragement and
support as students engage with the task at hand. He offers
guidance when a student is stuck and probes when
clarification is needed. After the student investigation,
the teacher highlights important ideas embedded in a
concrete problem, and summarizes and generalizes their
findings. In particular, the teacher’s summary makes sense
and is meaningful, because students have had the experience
of playing around with these ideas on their own before
coming together to formalize them as a class.

Moreover, the teacher repeatedly asks, “Did anyone get a
different answer?” or “Did anyone use a different method?”
to elicit multiple solutions strategies. This highlights the
connections between different problems, concepts, and areas
of mathematics and helps develop students’ mathematical
creativity. Creativity is further fostered through
acknowledging “good mistakes.” Students who make an error
are often commended for the progress they made and how their
work contributed to the discussion and to the collective
understanding of the class.

-- [[https://blogs.ams.org/matheducation/2015/01/10/the-hungarian-approach-and-how-it-fits-the-american-educational-landscape/][The Hungarian Approach and How It Fits the American
   Educational Landscape]] | On Teaching and Learning
   Mathematics
#+end_quote



 - Andrews, P., & Hatch, G. (2001). Hungary and its
   characteristic pedagogical flow. Proceedings of the
   British Congress of Mathematics Education, 21(2). 
   26-40. [[[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.659.7472&rep=rep1&type=pdf][pdf]]]
 - Stockton, J. C. (2010). Education of Mathematically
   Talented Students in Hungary. Journal of Mathematics
   Education at Teachers College, 1(2), 1-6. [[[http://journals.tc-library.org/index.php/matheducation/article/viewFile/574/354][pdf]]]


 - [[https://www.theguardian.com/teacher-network/2012/jul/20/primary-maths-programme][Exploring different approaches to teaching primary maths]] | The Guardian
 - [[https://matematiikkalehtisolmu.fi/2002/unkari/IJHUTSZ.html][Some Facts and Tendencies in the Hungarian Mathematics Teaching]] | Tibor Szalontai

** Blue Systems

 - [[https://www.bluegroup.systems/posts/2016-12-22-flipping-a-large-class-part-1/][Flipping a Large Class: Part 1]] | Blue Blog
 - [[https://www.internet-class.org/courses/fys/syllabus/][CSE 199 Syllabus]] | internet-class.org
 - internet-class.org
 - [[https://github.com/gchallen?tab=repositories][gchallen (Geoffrey Challen) / Repositories]]

 - [[https://www.ops-class.org/][ops-class.org | Learn Operating Systems Online]]

 /Tools/

 - LDAP?
 - [[https://auth0.com/][Single Sign On & Token Based Authentication]] | Auth0
  
 - [[https://www.discourse.org/][Discourse - Civilized Discussion]]
 - [[https://blog.discourse.org/2014/04/install-discourse-in-under-30-minutes/][Install Discourse in Under 30 Minutes]] 
 - [[https://hotcrp.com/][HotCRP.com]] | Conference review process
 - [[https://github.com/kohler/hotcrp][kohler/hotcrp: HotCRP conference review software]] | Github

