#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Mentorship 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/studyhall/sh-mentoring.org
:Created:   2017-11-12T18:31@Prek Leap (11.642600N-104.919210W)
:ID:        b21e69a0-ed3c-4a60-9af8-bb17f9ffc706
:VER:       563758364.845707274
:GEO:       48P-491193-1287029-15
:BXID:      proj:GHE5-1271
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction


 This post is about creating a presentation using hand drawn
 calligraphy, but the content of the presentation is a very good
 outline for training people to become mentors.

   - [[http://nibrahim.net.in/2017/11/04/pycon_india_2017_keynote.html][Creating a presentation by hand using calligraphy]] | Noufal
     Ibrahim
   - [[https://speakerdeck.com/nibrahim/mentoring-what-why-and-how-pycon-india-2017-keynote][Mentoring : What, Why, and How?]] | (PyCon India 2017 Keynote) //
     Speaker Deck

   - [[http://www.nationalmentoringresourcecenter.org/index.php/what-works-in-mentoring/resources-for-mentoring-programs.html][Resources for Mentoring Programs]] | National Mentoring
     Resourse Center



   - [[https://en.wikipedia.org/wiki/Mentorship][Mentorship]] | Wikipedia
   - [[https://en.wikipedia.org/wiki/Peer_mentoring][Peer mentoring]] | Wikipedia

   - [[bib:bozeman:2007toward][Toward a useful theory of mentoring: A conceptual analysis and critique]] | Barry Bozeman (2007) 
   - [[https://en.wikipedia.org/wiki/Letters_to_a_Young_Mathematician][Letters to a Young Mathematician]] | Wikipedia
   - [[https://en.wikipedia.org/wiki/Letters_to_a_Young_Poet][Letters to a Young Poet]] | Wikipedia
   - [[bib:rilke:2013letters][Letters to a Young Poet]] | Rainer Maria Rilke

There is a /huge/ number of books written on mentoring,


#+begin_quote
If mentoring theory disappoints, it is not for a lack of scholarly
attention or a deficit of published research.  By one accounting (J.
Allen & Johnston, 1997), more than 500 articles on mentoring were
published in management and education literatures during the 10 years
leading up to 1997.

-- [[bib:bozeman:2007toward][Toward a useful theory of mentoring: A conceptual analysis and critique]] | Barry Bozeman (2007) 
#+end_quote

 a lot of them
are little more than self-help books (hey it's trendy!) I found this
[[https://www.amazon.com/gp/richpub/listmania/fullview/R1O9Y3GAQDBRYO][list]] on Amazon which doesn't look half bad.


#+begin_quote
The crowd at the registration desk gathers, and now my watch
begins. It shall not end until the end of the sprints.

I shall speak no jargon, feign no surprise, well no actuallys, and
avoid all subtle isms.

I will remember what it was like to be a beginner.

I shall wear no crowns and seek no glory in geeking out with all my
conference mates, and instead will drop anything at a moment's notice
to help any beginner with sympathy, patience and a smile.

I am the mentor in the darkness.

I am the friendly coach in the halls.

I am the dunderinit for new happy programmers.

I pledge my life and honor to the Beginners Watch, for this day, and all the
scheduled conference days to come.

-- Harry Percival (@hjwp) & Nicholas Tollervey (@ntoll)
   [[https://www.youtube.com/watch?v=WI-BFxeumv8][Oath of the Mentor]] | YouTube
#+end_quote

Mentoring is one of those things that sound good and should
be simple, but is not.

What is the relationship between a student and mentor --
what is the mentor expected to help with?  

How do we actually train the mentor?

It's going to be difficult to get Cambodian students with
poor english communication skills to come out and tell
people they don't understand.

The video on learning a new language talked about a
"language parent":

   - works to understand what you're saying
   - does not correct mistakes
   - confirms understanding by using correct language
   - uses words the learners knows

A mentor is not the same as a teacher, they are there to
point the way and give alternative perspectives, not
formally teach course material.

A mentor is there to fill in the blanks in the material,
that is frustrating the student, but isn't being addressed
by the course material or structure.

A mentor provides feedback to the teachers on where
somethiing might be too easy or too difficult.

That said, the mentor get's a lot out of the relationship by
seeing the material through a beginners eyes and hopefully
from time to time will see things that they had forgotten or
never knew before.

I see the real value of a mentor as a coach that guides a
student through exercises.  Exercises are lonely and often
frustrating.

It's important to provide mentors from outside Cambodia with
enough context to understand the reality of life in
Cambodia.


To become a mentor:

  - application
  - profile
  - interview
  - mentorship training
