#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Thesis
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Thesis
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/studyhall/sh-thesis.org
:Created:  2017-11-22T09:16@Prek Leap (11.642600N-104.919210W)
:ID:       304e27a9-3066-4782-bc7a-51785e02facb
:VER:      564589052.590642737
:GEO:      48P-491193-1287029-15
:BXID:     proj:NHR7-4075
:Class:    deploy
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction
:PROPERTIES:
:ID:       a5f02a66-eaad-4e2e-a255-a6d7c179b992
:END:


The idea of a thesis is the ultimate and logical culmination of the
liberal arts and the very embodiment of the medieval /Trivium/.  A
thesis requires that the Trivium's three subjects, grammer, logic, and
rhetoric be used together to produce a singular work of scholarship or
scientific inquiry.  A knowledge of logic is required to frame
questions, investigate and research source material and evaluate that
material to make new insights.  A mastery of grammer provides the
knowledge of maniputing writing and other symbol systems to present
research and findings clearly so others can understand what has been
discovered.

It's sometimes forgotten that the oral defense of the thesis is
considered to be nearly as important as the written thesis.  This is
where rhetoric comes into play.  To convince in writing is a different
art from convincing in person.  And an oral defense of a proposition
takes place in real time.  During an oral defense you are either
prepared or not.  You either have mastered the material or you
haven't.  There is no inbetween.

** Audience

This book is for smart people who primarily work with information in
the form of text.  Text includes and represents nearly all forms of
information, or is used to generate other types of information in the
form of images.  This includes anything from writing prose (anything
in a written language), code, numbers, math, and other symbol systems.

There are those who believe that the end of the keyboard is nearly
apon us.  Such predictions are nothing new.  Many people thought that
automatic voice to text would be the killer app that would make
keyboards obsolete.  The new twist on these predictions is that you
won't even have to dictate, you'll be ale to write purely by thinking!

But this misses the entire point of written languages -- they are
called written and not printed languages for a reason.  Writing is a
physical process.  I remember many years ago reading a book that
interviewed dozens of famous writers on how they wrote and how they
thought about the process of writing.  A large number of writers 
described writing like a process of making something physical, as if
they were physically carving words into wood or stone.

Writing is both a conscious and unconscious process that is not a
one-to-one correspondence between spoken and written languages.  We as
a species now rely on both to do different things.

It's no accident that a thesis is both a written document that has to
be defended orally.

In /Preface to Plato/ Eric Havelock's theory that Homer's Iliad and
The Oddessy was from an oral tradition.  Homer was composed and passed
down to each generation through memorization.  What we call classical
Greece emerged at the time of Plato which correspondended to the first
generation of thinkers and artists who were grounded in what was to
become a written tradition and that the two were mutually exclusive.

It was the generation of the pre-socratics who wrested writing systems
from the scribes and accountants of the state to not only use writing
for accounting of grain and slaves, taxes and war booty for which it
had been invented and used for almost exlusively for xxx years before
being subverted and used to tell stories that recorded abstract ideas,
transcribed proscriptive knowledge, organized descriptive knowledge
and communicated observations, memories and emotions of human
experience to other people the author would never meet, and to future
readers born long after the author's death.



-------

More than anything, this is a book that extols a personal philosophy
of life, in which (though you may find this hard to believe at the
moment) emacs is a major part of.

Learning how to learn
Learning how to think critically
Learning how to think logically

Learning how to communicate

A thesis is where all of these skills come together through Research,
Composition and Editing


Dedicating yourself to a life in which you are constantly growing by
learning and challenging yourself to do more

Dedicating yourself to a life working on important problems

In one sense, this book is a bit like /Zen and the Art of Motorcycle
Maintenance/ that is ostensibly about how to fix motorcycles but is
really a framework for understanding the world and your place in it.

Mastery of a subject or discipline as the gateway to a life of
learning and exploration.

Practicing your art and science 

A Master's Toolbox
A Master's Toolchain
A Master's Workflow

** Saturation Job

** Everything Is Text
