#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Thesis
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Thesis
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/studyhall/sh-thesis.org
:Created:  2017-11-22T09:16@Prek Leap (11.642600N-104.919210W)
:ID:       304e27a9-3066-4782-bc7a-51785e02facb
:VER:      564589052.590642737
:GEO:      48P-491193-1287029-15
:BXID:     proj:NHR7-4075
:Class:    deploy
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction


The idea of a thesis is the ultimate and logical culmination of the
liberal arts and the very embodiment of the medieval /Trivium/.  A
thesis requires that the Trivium's three subjects, grammer, logic, and
rhetoric be used together to produce a singular work of scholarship or
scientific inquiry.  A knowledge of logic is required to frame
questions, investigate and research source material and evaluate that
material to make new insights.  A mastery of grammer provides the
knowledge of maniputing writing and other symbol systems to turn
present research and findings clearly so others can understand what
has been discovered.

It's sometimes forgotten that the oral defense of the thesis is
considered to be nearly as important as the written thesis.  This is
where rhetoric comes into play.  To convince in writing is a different
art from convincing in person.  And an oral defense of a proposition
takes place in real time.  During an oral defense you are either
prepared or not.  You either have mastered the material or you
haven't.  There is no inbetween.

